pagopa/eng-azure-governance

- README.md
- src/policy/02_policy_set_1_dev.tf
- src/policy/02_policy_set_2_uat.tf
- src/policy/02_policy_set_3_prod.tf
- src/policy/02_policy_set_4_devops.tf
- src/policy/03_policy_asingment_1_dev.tf
- src/policy/03_policy_asingment_2_uat.tf
- src/policy/03_policy_asingment_3_prod.tf
- src/policy/03_policy_asingment_4_devops.tf
Adesso esistono due tipi di risorse:
Policy set advice: perciò con regole che permettono di fare una consultazione
Policy set enforced: che forzano un comportamento per le risorse nuovo o che vengono aggiornate
> policy assigment type enforced and advice

- .pre-commit-config.yaml
- README.md
- src/.env/prod/terraform.tfvars
- src/policy/01_policy_root_definitions.tf
- src/policy/99_variables.tf
- src/policy/README.md
* Improved documentation about policies choosed
* Added documentation about structure and logic used into policies
> Improved documentation about policies choosed

- src/policy/02_policy_set_security_https_only.tf
added policy set
discover applications that don't use https
> https communication between applications

- src/.env/prod/terraform.tfvars
- src/policy/02_policy_set_security_certificate_lets_encrypt_only.tf
- src/policy/99_variables.tf
added policy set to check if inside the keyvault are present certificate issued by Let's Encrypt
> check let's encript as CA

- .github/workflows/static_analysis.yml
- .pre-commit-config.yaml
- src/policy/01_policy_root_definitions.tf
- src/policy/02_policy_set_0_root.tf
- src/policy/02_policy_set_1_dev.tf
- src/policy/02_policy_set_2_uat.tf
- src/policy/02_policy_set_3_prod.tf
- src/policy/02_policy_set_4_devops.tf
- src/policy/02_policy_set_security_certificate_lets_encrypt_only.tf
- src/policy/02_policy_set_security_https_only.tf
- src/policy/02_policy_set_security_not_public_endpoint.tf
- src/policy/02_policy_set_security_tls_1_2.tf
> feat: Devops_added_new_policy

- src/.env/prod/terraform.tfvars
- src/policy/02_policy_set_0_root.tf
- src/policy/02_policy_set_1_dev.tf
- src/policy/02_policy_set_2_uat.tf
- src/policy/02_policy_set_3_prod.tf
- src/policy/02_policy_set_4_devops.tf
- src/policy/02_policy_set_security_tls_1_2.tf
> complete clean

- src/policy/02_policy_set_1_dev.tf
- src/policy/02_policy_set_2_uat.tf
- src/policy/02_policy_set_3_prod.tf
- src/policy/02_policy_set_4_devops.tf
Add allowed locations for resource groups
Enforce geo-compliance requirements.
> feat: Add allowed locations for resource groups

- src/01_custom_roles/01_audit_logs.tf
- src/01_custom_roles/README.md
- src/02_policy_audit_logs/01_application_gateway.tf
- src/02_policy_audit_logs/01_keyvault.tf
- src/02_policy_audit_logs/99_data_source.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/application_gateway_log_analytics.json
- src/02_policy_audit_logs/policy_rules/application_gateway_storage_account.json
- src/02_policy_audit_logs/policy_rules/keyvault_log_analytics.json
- src/02_policy_audit_logs/policy_rules/keyvault_storage_account.json
- src/04_policy_assignments/03_pagamenti_servizi_prod.tf
> fix: Audit logs permissions and policy

- src/02_policy_audit_logs/01_container_registry.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/container_registry_log_analytics.json
- src/02_policy_audit_logs/policy_rules/container_registry_storage_account.json
- src/03_policy_set/01_audit_logs.tf
> feat: Add audit logs for Container Registry

- src/02_policy_audit_logs/01_kubernetes_cluster.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/kubernetes_cluster_log_analytics.json
- src/02_policy_audit_logs/policy_rules/kubernetes_cluster_storage_account.json
- src/03_policy_set/01_audit_logs.tf
Add audit logs for Kubernetes Cluster
Improve audit logs
> feat: Add audit logs for Kubernetes Cluster

- src/02_policy_audit_logs/01_api_management.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/api_management_log_analytics.json
- src/02_policy_audit_logs/policy_rules/api_management_storage_account.json
- src/03_policy_set/01_audit_logs.tf
Add audit logs for Api Management
Add audit logs policy
> feat: Add audit logs for Api Management

- src/02_policy_audit_logs/01_postgresql_flexible.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/postgresql_flexible_log_analytics.json
- src/02_policy_audit_logs/policy_rules/postgresql_flexible_storage_account.json
- src/03_policy_set/01_audit_logs.tf
Add Audit Logs for Postgresql Flexible
Audit log policy and remediations
> feat: Add Audit Logs for Postgresql Flexible

- src/02_policy_audit_logs/policy_rules/kubernetes_cluster_log_analytics.json
- src/02_policy_audit_logs/policy_rules/kubernetes_cluster_storage_account.json
> fix: Audit Logs for aks

- src/02_policy_audit_logs/01_postgresql_single_server.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/postgresql_single_server_log_analytics.json
- src/02_policy_audit_logs/policy_rules/postgresql_single_server_storage_account.json
- src/03_policy_set/01_audit_logs.tf
Add Audit logs for Postgresql Single Server
> feat: Add Audit logs for Postgresql Single Server

- src/02_policy_resource_lock/99_variables.tf
- src/02_policy_resource_lock/README.md
- src/02_policy_tags_inherit_from_subscription/99_variables.tf
- src/02_policy_tags_inherit_from_subscription/README.md
> chore: Change metadata_category_name

- src/02_policy_audit_logs/01_log_analytics.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/log_analytics_log_analytics.json
- src/02_policy_audit_logs/policy_rules/log_analytics_storage_account.json
- src/03_policy_set/01_audit_logs.tf
Add audit logs for Log Analytics Workspace
audit logs
> feat: Add audit logs for Log Analytics Workspace

- src/04_policy_assignments/03_assistenza_operations_prod.tf
- src/04_policy_assignments/README.md
> feat: Add Assistenza policy assignments

- src/02_policy_audit_logs/01_cosmos_db.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/cosmos_db_log_analytics.json
- src/02_policy_audit_logs/policy_rules/cosmos_db_storage_account.json
- src/03_policy_set/01_audit_logs.tf
> feat: Add cosmos db audit logs

- src/02_policy_audit_logs/01_app_service.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/app_service_log_analytics.json
- src/02_policy_audit_logs/policy_rules/app_service_storage_account.json
- src/03_policy_set/01_audit_logs.tf
> feat: Add App Service Audit Logs

- src/02_policy_audit_logs/policy_rules/app_service_log_analytics.json
- src/02_policy_audit_logs/policy_rules/app_service_storage_account.json
fix app service audit logs only for app service plan
> fix: App Service audit logs

- src/02_policy_audit_logs/01_event_hub.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/event_hub_log_analytics.json
- src/02_policy_audit_logs/policy_rules/event_hub_storage_account.json
- src/03_policy_set/01_audit_logs.tf
> feat: Add Event hub audit logs

- src/02_policy_audit_logs/01_public_ip.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/public_ip_log_analytics.json
- src/02_policy_audit_logs/policy_rules/public_ip_storage_account.json
- src/03_policy_set/01_audit_logs.tf
> feat: Add audit logs for Public IP

- src/02_policy_audit_logs/01_virtual_network_gateway.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/virtual_network_gateway_log_analytics.json
- src/02_policy_audit_logs/policy_rules/virtual_network_gateway_storage_account.json
- src/03_policy_set/01_audit_logs.tf
> feat: Add audit logs for Virtual Network Gateway

- src/02_policy_audit_logs/policy_rules/public_ip_log_analytics.json
- src/02_policy_audit_logs/policy_rules/public_ip_storage_account.json
> fix: Add all logs for public ip

- src/02_policy_audit_logs/01_grafana.tf
- src/02_policy_audit_logs/99_output.tf
- src/02_policy_audit_logs/README.md
- src/02_policy_audit_logs/policy_rules/grafana_log_analytics.json
- src/02_policy_audit_logs/policy_rules/grafana_storage_account.json
- src/03_policy_set/01_audit_logs.tf
> feat: Add Grafana audit logs

- .gitignore
- src/03_policy_set/01_storage_account_prod.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/01_pagopa.tf
- src/04_policy_assignments/03_assistenza_operations_prod.tf
- src/04_policy_assignments/03_pagamenti_servizi_cloud_dev.tf
- src/04_policy_assignments/03_pagamenti_servizi_cloud_prod.tf
- src/04_policy_assignments/03_pagamenti_servizi_prod.tf
- src/04_policy_assignments/03_security_itoperations_prod.tf
- src/04_policy_assignments/README.md
- Storage accounts should have the specified minimum TLS version (only TLS 1.2)
- Secure transfer to storage accounts should be enabled
- [Preview]: Storage account public access should be disallowed
- Storage accounts should be limited by allowed SKUs: "Standard_ZRS", "Standard_GRS", "Standard_RAGRS", "Standard_GZRS", "Standard_RAGZRS", "Premium_ZRS"
Eng Standard best practices
> feat: Add Storage account best practices

- src/02_policy_application_gateway/01_allowed_ciphersuites.tf
- src/02_policy_application_gateway/01_allowed_sku.tf
- src/02_policy_application_gateway/99_output.tf
- src/02_policy_application_gateway/README.md
- src/02_policy_application_gateway/policy_rules/allowed_ciphersuites_parameters.json
- src/02_policy_application_gateway/policy_rules/allowed_ciphersuites_policy.json
- src/03_policy_set/01_application_gateway_prod.tf
> feat: Add app gateway base policy

- src/01_custom_roles/01_authorization_reader.tf
- src/01_custom_roles/01_export_deployments_template.tf
- src/01_custom_roles/README.md
> feat: Add PagoPA Export Deployments Template role

- src/04_policy_assignments/99_locals.tf
for prod:
- allow container registry public network access
for dev:
- allow redis, key vault, container registry, api management, cosmos, storage account public network access
for prod:
- allow container registry public network access
Reduce policy recommendations
> fix: Add more exception for azure_security_benchmark

- src/01_custom_roles/01_export_deployments_template.tf
- src/01_custom_roles/01_iac_reader.tf
- src/01_custom_roles/README.md
> feat: Add IaC reader role

- src/01_custom_roles/01_iac_reader.tf
- src/01_custom_roles/README.md
- src/02_policy_application_gateway/README.md
- src/02_policy_audit_logs/README.md
- src/02_policy_resource_lock/README.md
- src/02_policy_tags_inherit_from_subscription/README.md
- src/03_policy_set/README.md
- src/04_policy_assignments/README.md
- pagopa iac reader (custom role): now have the possibility to generate aks credentials
Allow the identities that have this role to generate aks credentials
> feat: PagoPA IaC Reader custom role, now has the possibility to generate aks credentials

- CODEOWNERS
> chore: Change CODEOWNERS to cloud cloud-eng

- src/02_policy_application_gateway/01_required_zones.tf
- src/02_policy_application_gateway/99_output.tf
- src/02_policy_application_gateway/README.md
- src/02_policy_application_gateway/policy_rules/required_zones_parameters.json
- src/02_policy_application_gateway/policy_rules/required_zones_policy.json
- src/03_policy_set/01_application_gateway_prod.tf
> feat: Add app gateway multi az

- src/02_policy_event_hub/.terraform.lock.hcl
- src/02_policy_event_hub/01_required_network.tf
- src/02_policy_event_hub/99_data_source.tf
- src/02_policy_event_hub/99_main.tf
- src/02_policy_event_hub/99_output.tf
- src/02_policy_event_hub/99_terraform.tf
- src/02_policy_event_hub/99_terraform.tf.ci
- src/02_policy_event_hub/99_variables.tf
- src/02_policy_event_hub/README.md
- src/02_policy_event_hub/backend.ini
- src/02_policy_event_hub/policy_rules/required_network_parameters.json
- src/02_policy_event_hub/policy_rules/required_network_policy.json
- src/02_policy_event_hub/terraform.sh
- src/03_policy_set/01_event_hub_prod.tf
- src/03_policy_set/99_data_source.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/03_pagamenti_servizi_prod.tf
- src/04_policy_assignments/README.md
> feat: Add event hub network policy

- .github/workflows/static_analysis.yml
- src/02_policy_dns/.terraform.lock.hcl
- src/02_policy_dns/01_required_caa_record.tf
- src/02_policy_dns/99_data_source.tf
- src/02_policy_dns/99_main.tf
- src/02_policy_dns/99_output.tf
- src/02_policy_dns/99_terraform.tf
- src/02_policy_dns/99_terraform.tf.ci
- src/02_policy_dns/99_variables.tf
- src/02_policy_dns/README.md
- src/02_policy_dns/backend.ini
- src/02_policy_dns/policy_rules/required_caa_record_parameters.json
- src/02_policy_dns/policy_rules/required_caa_record_policy.json
- src/02_policy_dns/terraform.sh
- src/03_policy_set/01_application_gateway_prod.tf
- src/03_policy_set/01_dns.tf
- src/03_policy_set/01_event_hub_prod.tf
- src/03_policy_set/99_data_source.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/01_pagopa.tf
- src/04_policy_assignments/99_locals.tf
- src/04_policy_assignments/README.md
> feat: Add dns policy for CAA records

- src/02_policy_app_service/01_app_service_allowed_sku.tf
- src/02_policy_app_service/99_output.tf
- src/02_policy_app_service/README.md
- src/02_policy_app_service/policy_rules/allowed_app_service_sku_parameters.json
- src/02_policy_app_service/policy_rules/allowed_app_service_sku_policy.json
- src/02_policy_app_service/policy_rules/allowed_function_app_linuxfxversion_parameters.json
- src/03_policy_set/01_app_service_dev.tf
- src/03_policy_set/01_app_service_locals.tf
- src/03_policy_set/01_app_service_uat.tf
- src/03_policy_set/README.md
prod
- listofallowedsku  = ["WS1", "P0v3", "P1v3"]
- listofallowedkind = ["elastic", "linux"]
uat
- listofallowedsku  = ["Y1", "WS1", "B1", "B2", "B3"]
- listofallowedkind = ["elastic", "linux", "functionapp"]
dev
- listofallowedsku  = ["Y1", "WS1", "B1", "B2", "B3"]
- listofallowedkind = ["elastic", "linux", "functionapp"]
> feat: Policy per limitare le SKU degli app service plan

- src/02_policy_redis/01_allowed_sku.tf
- src/02_policy_redis/01_allowed_tls.tf
- src/02_policy_redis/01_disable_nosslport.tf
- src/02_policy_redis/99_output.tf
- src/02_policy_redis/README.md
- src/02_policy_redis/policy_rules/allowed_sku_parameters.json
- src/02_policy_redis/policy_rules/allowed_sku_policy.json
- src/02_policy_redis/policy_rules/allowed_tls_parameters.json
- src/02_policy_redis/policy_rules/allowed_tls_policy.json
- src/02_policy_redis/policy_rules/disable_nosslport_parameters.json
- src/02_policy_redis/policy_rules/disable_nosslport_policy.json
- src/03_policy_set/01_redis_dev.tf
- src/03_policy_set/01_redis_locals.tf
- src/03_policy_set/01_redis_uat.tf
- src/03_policy_set/README.md
https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F7803067c-7d34-46e3-8c79-0ca68fc4036d
https://ms.portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F470baccb-7e51-4549-8b1a-3e5be069f663
> feat: Redis policy allowed sku, disable nossl port, only tls 1.2

- src/02_policy_kubernetes/01_allowed_kubernetes_version.tf
- src/02_policy_kubernetes/01_required_image_sha256.tf
- src/02_policy_kubernetes/99_output.tf
- src/02_policy_kubernetes/README.md
- src/02_policy_kubernetes/policy_rules/allowed_kubernetes_version_parameters.json
- src/02_policy_kubernetes/policy_rules/allowed_kubernetes_version_policy.json
- src/02_policy_kubernetes/policy_rules/required_image_sha256_gatekeeper.yaml
- src/02_policy_kubernetes/policy_rules/required_image_sha256_parameters.json
- src/02_policy_kubernetes/policy_rules/required_image_sha256_policy.json
- src/03_policy_set/01_kubernetes_prod.tf
- src/03_policy_set/99_data_source.tf
- src/03_policy_set/README.md
> feat: Add k8s required sha256 and not allowed privileged containers

- src/02_policy_kubernetes/01_allowed_kubernetes_version.tf
- src/02_policy_kubernetes/policy_rules/allowed_kubernetes_version_parameters.json
- src/02_policy_kubernetes/policy_rules/allowed_kubernetes_version_policy.json
- src/03_policy_set/01_redis_prod.tf
> feat: Add redis networking and fix k8s version

- src/04_policy_assignments/03_pagamenti_servizi_prod.tf
- src/04_policy_assignments/README.md
> fix: CosmosDB policy assignments

- src/02_policy_data_sovereignty/.terraform.lock.hcl
- src/02_policy_data_sovereignty/01_allowed_locations.tf
- src/02_policy_data_sovereignty/01_allowed_locations_resource_group.tf
- src/02_policy_data_sovereignty/99_data_source.tf
- src/02_policy_data_sovereignty/99_main.tf
- src/02_policy_data_sovereignty/99_output.tf
- src/02_policy_data_sovereignty/99_terraform.tf
- src/02_policy_data_sovereignty/99_terraform.tf.ci
- src/02_policy_data_sovereignty/99_variables.tf
- src/02_policy_data_sovereignty/README.md
- src/02_policy_data_sovereignty/backend.ini
- src/02_policy_data_sovereignty/policy_rules/allowed_locations_parameters.json
- src/02_policy_data_sovereignty/policy_rules/allowed_locations_policy.json
- src/02_policy_data_sovereignty/policy_rules/allowed_locations_resource_groups_parameters.json
- src/02_policy_data_sovereignty/policy_rules/allowed_locations_resource_groups_policy.json
- src/02_policy_data_sovereignty/terraform.sh
- src/03_policy_set/01_data_sovereignty_eu.tf
- src/03_policy_set/99_data_source.tf
- src/03_policy_set/README.md
> feat: Enable North Italy

- src/03_policy_set/01_networking_locals.tf
- src/03_policy_set/01_networking_prod.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/03_pagamenti_servizi_prod.tf
- src/04_policy_assignments/99_locals.tf
- src/04_policy_assignments/README.md
> feat: Add DDoS protection plan policy

- src/02_policy_cosmosdb/01_required_zone_redundancy.tf
- src/02_policy_cosmosdb/99_output.tf
- src/02_policy_cosmosdb/README.md
- src/02_policy_cosmosdb/policy_rules/required_zone_redundancy_parameters.json
- src/02_policy_cosmosdb/policy_rules/required_zone_redundancy_policy.json
- src/03_policy_set/01_cosmosdb_prod.tf
> feat: TCE-90 Require AZ for CosmosDB

- src/02_policy_log_analytics/.terraform.lock.hcl
- src/02_policy_log_analytics/01_bound_daily_quota.tf
- src/02_policy_log_analytics/01_unbound_daily_quota.tf
- src/02_policy_log_analytics/99_data_source.tf
- src/02_policy_log_analytics/99_main.tf
- src/02_policy_log_analytics/99_output.tf
- src/02_policy_log_analytics/99_terraform.tf
- src/02_policy_log_analytics/99_terraform.tf.ci
- src/02_policy_log_analytics/99_variables.tf
- src/02_policy_log_analytics/README.md
- src/02_policy_log_analytics/backend.ini
- src/02_policy_log_analytics/policy_rules/bound_daily_quota_parameters.json
- src/02_policy_log_analytics/policy_rules/bound_daily_quota_policy.json
- src/02_policy_log_analytics/policy_rules/unbound_daily_quota_parameters.json
- src/02_policy_log_analytics/policy_rules/unbound_daily_quota_policy.json
- src/02_policy_log_analytics/terraform.sh
- src/03_policy_set/01_log_analytics_dev.tf
- src/03_policy_set/01_log_analytics_prod.tf
- src/03_policy_set/01_log_analytics_uat.tf
- src/03_policy_set/99_data_source.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/03_pagamenti_servizi_prod.tf
- src/04_policy_assignments/README.md
> feat: TCE-21 and TCE-96 enforce daily cap with respect to environment

- src/02_policy_audit_logs/policy_rules/api_management_storage_account.json
- src/02_policy_audit_logs/policy_rules/app_service_storage_account.json
- src/02_policy_audit_logs/policy_rules/application_gateway_storage_account.json
- src/02_policy_audit_logs/policy_rules/container_registry_storage_account.json
- src/02_policy_audit_logs/policy_rules/cosmos_db_storage_account.json
- src/02_policy_audit_logs/policy_rules/event_hub_storage_account.json
- src/02_policy_audit_logs/policy_rules/grafana_storage_account.json
- src/02_policy_audit_logs/policy_rules/keyvault_storage_account.json
- src/02_policy_audit_logs/policy_rules/kubernetes_cluster_storage_account.json
- src/02_policy_audit_logs/policy_rules/log_analytics_storage_account.json
- src/02_policy_audit_logs/policy_rules/postgresql_flexible_storage_account.json
- src/02_policy_audit_logs/policy_rules/postgresql_single_server_storage_account.json
- src/02_policy_audit_logs/policy_rules/public_ip_storage_account.json
- src/02_policy_audit_logs/policy_rules/subscription_storage_account.json
- src/02_policy_audit_logs/policy_rules/virtual_network_gateway_storage_account.json
> fix: TCE-102 Remove retention for audit logs to storage account

- src/03_policy_set/01_postgresql_prod.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/02_prod.tf
- src/04_policy_assignments/README.md
> feat: TCE-95 enforce georedundancy with PostgreSQL single node

- src/02_policy_postgresql/.terraform.lock.hcl
- src/02_policy_postgresql/01_required_flexible_georedundancy.tf
- src/02_policy_postgresql/99_data_source.tf
- src/02_policy_postgresql/99_main.tf
- src/02_policy_postgresql/99_output.tf
- src/02_policy_postgresql/99_terraform.tf
- src/02_policy_postgresql/99_terraform.tf.ci
- src/02_policy_postgresql/99_variables.tf
- src/02_policy_postgresql/README.md
- src/02_policy_postgresql/backend.ini
- src/02_policy_postgresql/policy_rules/required_flexible_georedundancy_parameters.json
- src/02_policy_postgresql/policy_rules/required_flexible_georedundancy_policy.json
- src/02_policy_postgresql/terraform.sh
- src/03_policy_set/01_postgresql_prod.tf
- src/03_policy_set/99_data_source.tf
- src/03_policy_set/README.md
> feat: TCE-24 require georedundancy for PostgreSQL Flexible

- src/03_policy_set/01_kubernetes_prod.tf
> feat: TCE-113 Enable Defender profile on AKS

- src/02_policy_kubernetes/01_required_defender_profile.tf
- src/02_policy_kubernetes/01_required_policy_addon.tf
- src/02_policy_kubernetes/99_output.tf
- src/02_policy_kubernetes/README.md
- src/02_policy_kubernetes/policy_rules/required_defender_profile_parameters.json
- src/02_policy_kubernetes/policy_rules/required_defender_profile_policy.json
- src/02_policy_kubernetes/policy_rules/required_policy_addon_parameters.json
- src/02_policy_kubernetes/policy_rules/required_policy_addon_policy.json
- src/03_policy_set/01_kubernetes_prod.tf
> feat: Refactor K8s policy set locals and fix Deny policy

- src/03_policy_set/01_key_vault_prod.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/02_prod.tf
- src/04_policy_assignments/README.md
> feat: Add Key vault policy set

- src/03_policy_set/01_app_service_dev.tf
- src/03_policy_set/01_app_service_prod.tf
- src/03_policy_set/01_app_service_uat.tf
> feat: Add TLS/HTTPS policy for App service Function

- src/03_policy_set/01_kubernetes_prod.tf
> fix: K8s deny app armor

- src/02_policy_api_management/.terraform.lock.hcl
- src/02_policy_api_management/01_allowed_versions.tf
- src/02_policy_api_management/99_data_source.tf
- src/02_policy_api_management/99_main.tf
- src/02_policy_api_management/99_output.tf
- src/02_policy_api_management/99_terraform.tf
- src/02_policy_api_management/99_terraform.tf.ci
- src/02_policy_api_management/99_variables.tf
- src/02_policy_api_management/README.md
- src/02_policy_api_management/backend.ini
- src/02_policy_api_management/policy_rules/allowed_versions_parameters.json
- src/02_policy_api_management/policy_rules/allowed_versions_policy.json
- src/02_policy_api_management/terraform.sh
- src/03_policy_set/01_api_management_dev.tf
- src/03_policy_set/01_api_management_prod.tf
- src/03_policy_set/01_api_management_uat.tf
- src/03_policy_set/99_data_source.tf
- src/03_policy_set/README.md
> feat: TCE-140 Require specific versions of API Management

- src/03_policy_set/01_networking_prod.tf
> feat: TCE-142 Require AAD identities on VPN Gateway for auth

- src/03_policy_set/01_storage_account_prod.tf
> fix: Storage account force secure transfer enabled

- src/01_custom_roles/01_policy_exempt.tf
- src/01_custom_roles/README.md
> faet: Add policy excemion

- src/03_policy_set/01_api_management_dev.tf
- src/03_policy_set/01_api_management_prod.tf
- src/03_policy_set/01_api_management_uat.tf
> feat: TCE-138 Require internal API Management

- src/02_policy_api_management/01_require_vnet.tf
- src/02_policy_api_management/99_output.tf
- src/02_policy_api_management/README.md
- src/02_policy_api_management/policy_rules/require_vnet_parameters.json
- src/02_policy_api_management/policy_rules/require_vnet_policy.json
- src/03_policy_set/01_api_management_dev.tf
- src/03_policy_set/01_api_management_prod.tf
- src/03_policy_set/01_api_management_uat.tf
> fix: TCE-138 Change API Managment require VNET approach

- src/03_policy_set/01_storage_account_prod.tf
> fix: Remove GRS, RAGRS from allowed storage skus

- src/01_custom_roles/01_ddos_joiner.tf
- src/01_custom_roles/README.md
> feat: Add PagoPA DDoS joiner Azure Role

- src/02_policy_audit_logs/policy_rules/api_management_log_analytics.json
- src/02_policy_audit_logs/policy_rules/api_management_storage_account.json
> fix: New apim policy for audit logs

- src/01_custom_roles/01_dns_zone_reader.tf
Add DNS Zone Reader role for DNS Takeover Project
> feat: Add DNS Zone Reader

- src/01_custom_roles/README.md
- src/03_policy_set/01_kubernetes_prod.tf
> fix: Add elastic excluded_namespaces in k8s disable_privileged_containers

- src/01_custom_roles/01_apim_list_secrets.tf
- src/01_custom_roles/README.md
Added custom roles definition into `01_custom_roles` folder.
To permit least privilege for RBAC we can define custom roles, the added role is to list secrets, useful to avoid Role `API Management Service Contributor` for a CI identity, with this we can use `API Management Service Reader` in combo with new one `PagoPA API Management Service List Secrets`
> feat: Added custom role for APIM list secrets [CES-614] 

- src/02_policy_cosmosdb/01_dynamic_scaling_enabled.tf
- src/02_policy_cosmosdb/99_output.tf
- src/02_policy_cosmosdb/README.md
- src/02_policy_cosmosdb/dynamic_scaling_enabled.tf
- src/02_policy_cosmosdb/policy_rules/dynamic_scaling_enabled_parameters.json
- src/02_policy_cosmosdb/policy_rules/dynamic_scaling_enabled_policy.json
- src/03_policy_set/01_cosmosdb_prod.tf
> feat: Cosmos dynamic scaling policy

- src/03_policy_set/01_cosmosdb_dev.tf
- src/03_policy_set/01_cosmosdb_uat.tf
- src/03_policy_set/README.md
- src/04_policy_assignments/modules/dev/01_cosmosdb.tf
- src/04_policy_assignments/modules/dev/README.md
- src/04_policy_assignments/modules/uat/01_cosmosdb.tf
- src/04_policy_assignments/modules/uat/README.md
> fix: Cosmosdb dynamic scaling policy for dev and uat

- src/03_policy_set/01_data_sovereignty_eu.tf
Add GermanyWestCentral in allowed location list
GermanyWestCentral is a valid location under EU
> feat: Add GermanyWestCentral in allowed location list

- src/02_policy_kubernetes/policy_rules/allowed_version_parameters.json
> fix: K8s allowed versions

- .identity/02_identity_prod_auth.tf
- src/01_custom_roles/01_policy_reader.tf
- src/01_custom_roles/01_policy_remediator.tf
- src/01_custom_roles/README.md
> feat: Add PagoPA Policy Reader and Remediator for scheduled policy remediation

- src/01_custom_roles/01_log_analytics_table_reader.tf
- src/01_custom_roles/README.md
> feat: Log Analytics table reader role

- .github/workflows/policy_remediation.yml
> feat: Add slack notification for workflows

- src/02_policy_cosmosdb/policy_rules/allowed_capacity_mode_policy.json
- src/02_policy_data_sovereignty/policy_rules/allowed_locations_policy.json
> feat: Allow new microsoft external entraid (CIAM)

- src/04_policy_assignments/02_dev.tf
- src/04_policy_assignments/02_prod.tf
> feat: Add devex subscriptions

- src/02_policy_app_service/policy_rules/allowed_function_app_linuxfxversion_parameters.json
> feat: Update functionapp linuxfxversion with dotnet-isolated

- src/03_policy_set/.terraform.lock.hcl
- src/03_policy_set/01_app_service_dev.tf
- src/03_policy_set/01_app_service_prod.tf
- src/03_policy_set/01_app_service_uat.tf
- src/03_policy_set/99_main.tf
- src/03_policy_set/99_terraform.tf
- src/03_policy_set/99_terraform.tf.ci
- src/03_policy_set/99_variables.tf
- src/03_policy_set/README.md
- src/03_policy_set/terraform.sh
> feat: Use previous version policy tls 12 for apps and function

- src/scripts/update_container_app_job_graph.sh
> fix: Mask output container job updated

- src/04_policy_assignments/02_prod.tf
- src/04_policy_assignments/README.md
> Exemption prodict capp svc lb ip

- src/01_custom_roles/01_static_web_app_list_secrets.tf
Add action listAppSettings to static web apps role
> feat: Add action listAppSettings to static web apps role
